import assert from 'node:assert/strict';
import { test } from 'node:test';
import { PublicCampus, publicCampusFetch, parseSpaces } from '../src/public-campus.js';
const software='<h1>Software Finder</h1><a href="/package/12"><h3 class="card_title">Example editor</h3><div class="card_desc">Draw diagrams</div><div class="toast-header"><small>Groen</small></div></a>';
test('software search keeps exact official IDs and paginates local matches',async()=>{const api=new PublicCampus(async()=>software);const r=await api.software('diagram',0);assert.equal(r.items[0]?.id,'12');assert.equal(r.complete,true);assert.match(r.coverage,/entitlement/);await assert.rejects(api.software('',-1),{code:'INVALID_RANGE'});});
test('software detail extracts official guidance without scripts or credential links',async()=>{const api=new PublicCampus(async()=>'<div class="col-sm-9"><h3><strong>Example</strong></h3><p>Install from the portal.</p><a href="https://example.com/?token=secret">Help</a><script>bad secret</script></div>');const r=await api.softwareDetail('12');assert.equal(r.name,'Example');assert.doesNotMatch(JSON.stringify(r),/secret|<script/);await assert.rejects(api.softwareDetail('../private'),{code:'INVALID_ID'});});
test('room data preserves zero capacities and does not claim availability',async()=>{const cells=['<a href="/space/8">Example Hall</a>','Example building','Teaching','Hall','20','0','0','Fixed','','Projector','Whiteboard','','WiFi','','Pool','42'];const html='<table><thead><tr><th>Name</th></tr></thead><tbody><tr><td>picture</td>'+cells.map(x=>'<td>'+x+'</td>').join('')+'</tr></tbody></table>';const r=await new PublicCampus(async()=>html).rooms('hall');assert.equal(r.items[0]?.examSeats,0);assert.equal(r.items[0]?.seats,20);assert.equal(r.liveAvailability,false);});
test('unknown page formats fail instead of returning an empty list',async()=>{const api=new PublicCampus(async()=>'<html>Sign in</html>');await assert.rejects(api.software('editor'),{code:'PUBLIC_FORMAT_CHANGED'});await assert.rejects(api.rooms('hall'),{code:'PUBLIC_FORMAT_CHANGED'});assert.throws(()=>parseSpaces('<html></html>'),{code:'PUBLIC_FORMAT_CHANGED'});});
test('ICT reads preserve dates and closed status and reject malformed pagination',async()=>{const body={count:1,next:null,results:[{id:1,title_EN:'Example maintenance',description_EN:'<p>Planned work</p>',closed:false,creation_date:'2026-10-01',from_date:'2026-10-02',status_update:[],faculty:[],impact:{title_EN:'Low'}}]};const r=await new PublicCampus(async()=>JSON.stringify(body)).notices('maintenance');assert.equal(r.items[0]?.closed,false);assert.equal(r.complete,true);assert.equal(r.items[0]?.publishedAt,'2026-10-01');assert.match(r.coverage,/not.*health/i);await assert.rejects(new PublicCampus(async()=>JSON.stringify({...body,count:2})).notices('maintenance'),{code:'PUBLIC_FORMAT_CHANGED'});});
test('public transport rejects unobserved routes before network access',async()=>{let calls=0;const fetcher=async()=>{calls++;return new Response('ok');};for(const url of ['https://evil.example/','http://softwarefinder.tudelft.nl/','https://softwarefinder.tudelft.nl/private','https://softwarefinder.tudelft.nl/?token=x'])await assert.rejects(publicCampusFetch(url,fetcher as typeof fetch),{code:'INVALID_PUBLIC_ROUTE'});assert.equal(calls,0);});
test('public transport is credential-free, refuses redirects and bounds response bytes',async()=>{await publicCampusFetch('https://softwarefinder.tudelft.nl/',async(_url,options)=>{assert.equal(options?.redirect,'error');assert.equal(options?.credentials,'omit');assert.equal(new Headers(options?.headers).has('Authorization'),false);return new Response('ok',{headers:{'content-type':'text/html'}});});await assert.rejects(publicCampusFetch('https://softwarefinder.tudelft.nl/',async()=>new Response('x'.repeat(2100000),{headers:{'content-type':'text/html'}})),{code:'PUBLIC_RESPONSE_LIMIT'});});
function nuxtFixture(root: unknown) { const values: unknown[]=[]; const encode=(value: unknown): number=>{const i=values.length;values.push(null);values[i]=Array.isArray(value)?value.map(encode):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,encode(v)])):value;return i;};encode(root);return '<script id="__NUXT_DATA__" type="application/json">'+JSON.stringify(values)+'</script>'; }
test('Spacefinder decoding exposes only selected catalogue fields',async()=>{const html=nuxtFixture({pinia:{spaces:{buildingsI18n:[{number:'42',i18n:{en:{name:'Example faculty'}}}],spacesI18n:[{spaceId:'S1',buildingNumber:'42',i18n:{en:{name:'Study hall',remark:''}},seats:30,facilities:{daylit:true,quietness:'quiet'},exchangeBuildingId:'private@example.invalid'}]}}});const r=await new PublicCampus(async()=>html).spaces('quiet');assert.equal(r.items[0]?.building,'Example faculty');assert.equal(r.total,1);assert.equal(r.liveAvailability,false);assert.doesNotMatch(JSON.stringify(r),/private@example/);});
test('cyclic or unsupported Nuxt payloads fail within bounds',()=>{for(const payload of ['[{"pinia":0}]','[]','["unexpected"]'])assert.throws(()=>parseSpaces('<script id="__NUXT_DATA__">'+payload+'</script>'),{code:'PUBLIC_FORMAT_CHANGED'});});
test('public service failures and wrong MIME types are sanitized',async()=>{for(const request of [async()=>{throw new Error('secret URL');},async()=>new Response('login',{status:403}),async()=>new Response('binary',{headers:{'content-type':'application/octet-stream'}})])await assert.rejects(publicCampusFetch('https://softwarefinder.tudelft.nl/',request as typeof fetch),{code:'PUBLIC_UNAVAILABLE'});});
test('ICT pagination does not follow an arbitrary next URL',async()=>{const body={count:2,next:'https://evil.example/',results:[]};await assert.rejects(new PublicCampus(async()=>JSON.stringify(body)).notices('incidents'),{code:'PUBLIC_FORMAT_CHANGED'});await assert.rejects(new PublicCampus(async()=>'{oops').notices('incidents'),{code:'PUBLIC_FORMAT_CHANGED'});});
